// Code generated by hertz generator.

package ledger

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ledger "ledger/biz/model/hello/ledger"
)

// HelloMethod2 .
// @router /hello [GET]
func HelloMethod2(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ledger.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ledger.HelloResp)

	c.JSON(consts.StatusOK, resp)
}
