// Code generated by hertz generator.

package ledger

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod2Mw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		TestMw,
	}
}

func _hellomethod20Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethod3Mw() []app.HandlerFunc {
	// your code...
	return nil
}
